# Generated by Django 4.2.11 on 2024-04-15 11:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddMount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(default='пер.', max_length=255, verbose_name='Красивое название')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('other_titles', models.CharField(max_length=255, verbose_name='Другое название')),
                ('connect', models.CharField(default='', max_length=1)),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('status', models.CharField(choices=[('NW', 'Новый'), ('AC', 'На модерации'), ('PN', 'Принят'), ('RJ', 'Отклонён')], default='NW', max_length=2, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=34.3, help_text='Широта в градусах', validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Широта')),
                ('longitude', models.FloatField(default=61.8, help_text='Долгота в градусах', validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Долгота')),
                ('height', models.IntegerField(default=0, help_text='Высота в метрах над уровнем моря', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8848)], verbose_name='Высота')),
            ],
        ),
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(blank=True, choices=[('1a', '1А'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б')], max_length=6, null=True, verbose_name='Зима')),
                ('summer', models.CharField(blank=True, choices=[('1a', '1А'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б')], max_length=6, null=True, verbose_name='Лето')),
                ('autumn', models.CharField(blank=True, choices=[('1a', '1А'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б')], max_length=6, null=True, verbose_name='Осень')),
                ('spring', models.CharField(blank=True, choices=[('1a', '1А'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б'), ('3a', '3А'), ('3b', '3Б')], max_length=6, null=True, verbose_name='Весна')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('otc', models.CharField(max_length=100, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=100, verbose_name='Почта')),
                ('phone', models.IntegerField(unique=True, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('images', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото')),
                ('mount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_mount', to='sprint.addmount', verbose_name='Фото перевала')),
            ],
        ),
        migrations.AddField(
            model_name='addmount',
            name='coord',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mount_coord', to='sprint.coords', verbose_name='Координаты'),
        ),
        migrations.AddField(
            model_name='addmount',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sprint.difficultylevel', verbose_name='Уровень сложности'),
        ),
        migrations.AddField(
            model_name='addmount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mount_user', to='sprint.user', verbose_name='Автор'),
        ),
    ]
