# Generated by Django 4.2.11 on 2024-04-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0002_rename_images_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmount',
            name='connect',
            field=models.CharField(blank=True, default='', max_length=1, null=True),
        ),
    ]
