# Generated by Django 4.2.11 on 2024-04-21 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sprint', '0003_alter_addmount_connect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='mount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sprint.addmount', verbose_name='Фото перевала'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(verbose_name='Телефон'),
        ),
    ]
